Repository elastic/elasticsearch-php, pull requests merged in 2019-08, with the labels that each got.

#927 Fix #922 for php_uname disabled
  src/Elasticsearch/Connections/Connection.php
Labels: 7.0

#933 Prepare for 7.2.0 release
  .travis.yml
  src/Elasticsearch/Client.php
  src/Elasticsearch/Endpoints/Cluster/Health.php
  src/Elasticsearch/Endpoints/FieldCaps.php
  src/Elasticsearch/Endpoints/Indices/Close.php
  src/Elasticsearch/Endpoints/Indices/Stats.php
  src/Elasticsearch/Namespaces/CatNamespace.php
  src/Elasticsearch/Namespaces/ClusterNamespace.php
  src/Elasticsearch/Namespaces/IndicesNamespace.php
  src/Elasticsearch/Namespaces/IngestNamespace.php
  src/Elasticsearch/Namespaces/NodesNamespace.php
  src/Elasticsearch/Namespaces/RemoteNamespace.php
  src/Elasticsearch/Namespaces/SnapshotNamespace.php
  src/Elasticsearch/Namespaces/TasksNamespace.php
  tests/Elasticsearch/Tests/YamlRunnerTest.php
  util/GenerateParamDocs.php
Labels: 7.0

#938 Missing Implementation for Doc Examples
  examples/47b5ff897f26e9c943cee5c06034181d.adoc
  examples/c5e5873783246c7b1c01d8464fed72c4.adoc
  examples/d90a84a24a407731dfc1929ac8327746.adoc
  examples/docs/src/Examples/Docs/Docs/Get.php
Labels: Documentation

#939 [Backport] Add missing Doc Example
  examples/47b5ff897f26e9c943cee5c06034181d.adoc
  examples/c5e5873783246c7b1c01d8464fed72c4.adoc
  examples/d90a84a24a407731dfc1929ac8327746.adoc
  examples/docs/src/Examples/Docs/Docs/Get.php
Labels: 7.0, Documentation
