Repository elastic/elasticsearch-php, pull requests merged in 2020-02, with the labels that each got.

#995 [DOCS] Fix broken link to scroll docs
  docs/search-operations.asciidoc
Labels: bug

#1000 Adds shared/attributes.asciidoc to index
  docs/index.asciidoc
Labels: 7.0, 8.0

#1001 [7.x] Adds shared/attributes.asciidoc to index
  docs/index.asciidoc
Labels: 7.0, Documentation

#999 [DOCS] Fine-tunes overview and quick start in PHP client book
  docs/overview.asciidoc
  docs/quickstart.asciidoc
Labels: 7.0, Documentation

#1004 [7.x][DOCS] Fine-tunes install and configuration sections in the PHP client book
  docs/configuration.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
Labels: 7.0, Documentation
