Repository elastic/elasticsearch-php, pull requests merged in 2021-05, with the labels that each got.

#1129 [DOCS] Adds Helpers section to PHP book
  docs/breaking-changes.asciidoc
  docs/community.asciidoc
  docs/configuration.asciidoc
  docs/helpers.asciidoc
  docs/index.asciidoc
  docs/overview.asciidoc
  docs/php_json_objects.asciidoc
Labels: 7.x, 8.0, Documentation

#1132 [DOCS] Adds Release notes section to PHP book
  docs/index.asciidoc
  docs/release-notes.asciidoc
Labels: 7.x, 8.0, Documentation

#1139 [7.x][DOCS] Adds Helpers section to PHP book
  docs/breaking-changes.asciidoc
  docs/community.asciidoc
  docs/configuration.asciidoc
  docs/helpers.asciidoc
  docs/index.asciidoc
  docs/overview.asciidoc
  docs/php_json_objects.asciidoc
Labels: 7.x, Documentation, backport 7.x

#1140 [7.x] [DOCS] Adds Release notes section to PHP book
  docs/index.asciidoc
  docs/release-notes.asciidoc
Labels: 7.x, Documentation, backport 7.x

#1137 [DOCS] Adds section about PSR 7
  docs/overview.asciidoc
Labels: 8.0, Documentation

#1142 Add support for API Compatibility Header
  src/Elasticsearch/ClientBuilder.php
  tests/Elasticsearch/Tests/ClientBuilderTest.php
Labels: 7.x, backport 7.13
