Repository elastic/elasticsearch-php, pull requests merged in 2025-04, with the labels that each got.

#1444 [docs] Add missing mapped pages
  docs/release-notes/breaking-changes.md
Labels: Documentation

#1447 [docs] Fix image paths for docs-assembler
  docs/reference/connecting.md
  docs/reference/getting-started.md
Labels: Documentation, backport 9.0

#1448 Updated docs for 9.0.0 release
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  tests/test_to_skip.php
Labels: backport 9.0
